language: ruby
cache: bundler

matrix:
  include:
    - rvm: 2.3
    - rvm: 2.4
    - rvm: 2.5
    - rvm: 2.6
    - rvm: 2.6
      os: osx
      env:
        # TODO: 0.8 is enough on Linux, but 2 seems needed for Travis/OSX
        - LISTEN_TESTS_DEFAULT_LAG=2
    - rvm: jruby
    - rvm: truffleruby
    - rvm: truffleruby-head
    - rvm: ruby-head
  allow_failures:
    - rvm: truffleruby
    - rvm: truffleruby-head
    - rvm: jruby
    - rvm: ruby-head
  fast_finish: true
